// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUu2oALXVV66WR-dnz-YPmmmkH7ZAmlhs',
    appId: '1:468919974199:web:23b033635cc913b04e82b2',
    messagingSenderId: '468919974199',
    projectId: 'zerome',
    authDomain: 'zerome.firebaseapp.com',
    storageBucket: 'zerome.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjKxK7rIK7VYqlZDxxfCAFff02nHdvobQ',
    appId: '1:468919974199:android:3220c3cf0f470f394e82b2',
    messagingSenderId: '468919974199',
    projectId: 'zerome',
    storageBucket: 'zerome.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvMlPWLJjC8Rl3Q_slR3N09qUje_Z9R2M',
    appId: '1:468919974199:ios:165ea13eb03100384e82b2',
    messagingSenderId: '468919974199',
    projectId: 'zerome',
    storageBucket: 'zerome.firebasestorage.app',
    iosBundleId: 'com.example.zaroMeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvMlPWLJjC8Rl3Q_slR3N09qUje_Z9R2M',
    appId: '1:468919974199:ios:165ea13eb03100384e82b2',
    messagingSenderId: '468919974199',
    projectId: 'zerome',
    storageBucket: 'zerome.firebasestorage.app',
    iosBundleId: 'com.example.zaroMeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUu2oALXVV66WR-dnz-YPmmmkH7ZAmlhs',
    appId: '1:468919974199:web:915fe1bdf58547314e82b2',
    messagingSenderId: '468919974199',
    projectId: 'zerome',
    authDomain: 'zerome.firebaseapp.com',
    storageBucket: 'zerome.firebasestorage.app',
  );
}
